apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T09:34:00Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "5644"
  uid: 021a861b-835b-4fa0-a07b-48d0fdf2c3b0
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.184.223
  clusterIPs:
  - 10.110.184.223
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31962
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
